In [2]:
#토픽은 주제다. 토픽모델링이란 기계학습 및 자연어 처리 분야에서 토픽이라는 문서집합의 추상적인 주제를 발견하기 위한 통계적 모델
#텍스트 본문의 숨겨진 의미구조를 발견하기 위해 사용되는 텍스트 마이닝 기법입니다.

#잠재의미분석

import numpy as np
#4X9행렬
A=np.array([[0,0,0,1,0,1,1,0,0],[0,0,0,1,1,0,1,0,0],[0,1,1,0,2,0,0,0,0],[1,0,0,0,0,0,0,1,1]])
np.shape(A)

(4, 9)

In [3]:
U,s,VT=np.linalg.svd(A,full_matrices=True)
print(U.round(2)) #소수점길이조절

[[-0.24  0.75  0.   -0.62]
 [-0.51  0.44 -0.    0.74]
 [-0.83 -0.49 -0.   -0.27]
 [-0.   -0.    1.    0.  ]]


In [4]:
print(s.round(2))

[2.69 2.05 1.73 0.77]


In [5]:
S=np.zeros((4,9))
S[:4,:4]=np.diag(s) #특이값을 대각행렬에 삽입
print(S.round(2))

[[2.69 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   2.05 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   1.73 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.77 0.   0.   0.   0.   0.  ]]


In [6]:
print(VT.round(2))

[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]
 [ 0.58 -0.    0.    0.   -0.    0.   -0.    0.58  0.58]
 [ 0.   -0.35 -0.35  0.16  0.25 -0.8   0.16 -0.   -0.  ]
 [-0.   -0.78 -0.01 -0.2   0.4   0.4  -0.2   0.    0.  ]
 [-0.29  0.31 -0.78 -0.24  0.23  0.23  0.01  0.14  0.14]
 [-0.29 -0.1   0.26 -0.59 -0.08 -0.08  0.66  0.14  0.14]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19  0.75 -0.25]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19 -0.25  0.75]]


In [8]:
np.allclose(A,np.dot(np.dot(U,S),VT).round(2)) #두개의 행렬이 동일하면 True

True

In [9]:
S=S[:2,:2]
print(S.round(2))

[[2.69 0.  ]
 [0.   2.05]]


In [10]:
U=U[:,:2]
print(U.round(2))

[[-0.24  0.75]
 [-0.51  0.44]
 [-0.83 -0.49]
 [-0.   -0.  ]]


In [11]:
VT=VT[:2,:]
print(VT.round(2))

[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]]


In [12]:
A_prime=np.dot(np.dot(U,S),VT)
print(A)
print(A_prime.round(2))
#둘은 다른 결과가 나온다. 

[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]
[[ 0.   -0.17 -0.17  1.08  0.12  0.62  1.08 -0.   -0.  ]
 [ 0.    0.2   0.2   0.91  0.86  0.45  0.91  0.    0.  ]
 [ 0.    0.93  0.93  0.03  2.05 -0.17  0.03  0.    0.  ]
 [ 0.    0.    0.    0.    0.   -0.    0.    0.    0.  ]]


In [13]:
#실습을 통한 이해
#20개의 다른 주제를 가진 뉴스그룹 데이터 Twenty Newsgroups
#LSA를 사용해서 문서의 수를 원하는 토픽의 수로 압축한 뒤에 각 토픽당 가장 중요한 단어 5개를 출력하는 실습

import pandas as pd
from sklearn.datasets import fetch_20newsgroups
dataset=fetch_20newsgroups(shuffle=True,random_state=1,remove=('headers','footers','quotes'))
documents=dataset.data
len(documents)

11314

In [15]:
documents[1]

"\n\n\n\n\n\n\nYeah, do you expect people to read the FAQ, etc. and actually accept hard\natheism?  No, you need a little leap of faith, Jimmy.  Your logic runs out\nof steam!\n\n\n\n\n\n\n\nJim,\n\nSorry I can't pity you, Jim.  And I'm sorry that you have these feelings of\ndenial about the faith you need to get by.  Oh well, just pretend that it will\nall end happily ever after anyway.  Maybe if you start a new newsgroup,\nalt.atheist.hard, you won't be bummin' so much?\n\n\n\n\n\n\nBye-Bye, Big Jim.  Don't forget your Flintstone's Chewables!  :) \n--\nBake Timmons, III"

In [16]:
print(dataset.target_names)
#위와 같은 형식의 샘플이 11,314개 존재한다. 사이킷런이 제공하는 뉴스그룹 데이터에서 
#target_name에는 본래 이 뉴스그룹데이터가 어떤 20개의 카테고리를 갖고있었는지가 저장되어져 있다. 


['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [17]:
#텍스트 전처리
news_df=pd.DataFrame({'document':documents})
#특수문자
news_df['clean_doc']=news_df['document'].str.replace("[^a-zA-Z]", " ")
#길이가 3이하인 단어는 제거
news_df['clean_doc']=news_df['clean_doc'].apply(lambda x:' '.join([w for w in x.split() if len(w)>3]))
#전체 단어에 대한 소문자 변환
news_df['clean_doc']=news_df['clean_doc'].apply(lambda x:x.lower())
#데이터 정제끝!

In [18]:
news_df['clean_doc'][1]

'yeah expect people read actually accept hard atheism need little leap faith jimmy your logic runs steam sorry pity sorry that have these feelings denial about faith need well just pretend that will happily ever after anyway maybe start newsgroup atheist hard bummin much forget your flintstone chewables bake timmons'

In [19]:
#이제 불용어를 제거하자
from nltk.corpus import stopwords
stop_words=stopwords.words('english')#NLTK로부터 불용어를 받아온다. 
tokenized_doc=news_df['clean_doc'].apply(lambda x:x.split())#토큰화
tokenized_doc=tokenized_doc.apply(lambda x:[item for item in x if item not in stop_words])
#불용어제거!
print(tokenized_doc[1])

['yeah', 'expect', 'people', 'read', 'actually', 'accept', 'hard', 'atheism', 'need', 'little', 'leap', 'faith', 'jimmy', 'logic', 'runs', 'steam', 'sorry', 'pity', 'sorry', 'feelings', 'denial', 'faith', 'need', 'well', 'pretend', 'happily', 'ever', 'anyway', 'maybe', 'start', 'newsgroup', 'atheist', 'hard', 'bummin', 'much', 'forget', 'flintstone', 'chewables', 'bake', 'timmons']


In [22]:
#TF-IDF행렬 만들기
#불용어 제거를 위해 토큰화 작업을 수행했지만 TF-IDF행렬을 만들기위해 다시 토큰화작업을 역으로 취소하는 작업을 수행
#역토큰화

detokenized_doc=[]
for i in range(len(news_df)):
    t=' '.join(tokenized_doc[i])
    detokenized_doc.append(t)
news_df['clean_doc']=detokenized_doc
news_df['clean_doc'][1]
#불용어가 제거된 상태에서 역토큰화가 수행되었음.

'yeah expect people read actually accept hard atheism need little leap faith jimmy logic runs steam sorry pity sorry feelings denial faith need well pretend happily ever anyway maybe start newsgroup atheist hard bummin much forget flintstone chewables bake timmons'

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(stop_words='english',max_features=1000,max_df=0.5,smooth_idf=True) #상위 1000개의 단어 보존
X=vectorizer.fit_transform(news_df['clean_doc'])
X.shape

(11314, 1000)

In [27]:
#토픽 모델링
#절단된 SVD사용. 차원을 축소한다.  20개의 카테고리를 갖고 있었기 때문에
#20개의 토픽을 가졌다고 가정하고 토픽모델링 시도.

from sklearn.decomposition import TruncatedSVD
svd_model=TruncatedSVD(n_components=20,algorithm='randomized',n_iter=100,random_state=122)
svd_model.fit(X)
len(svd_model.components_)

20

In [28]:
np.shape(svd_model.components_)

(20, 1000)

In [31]:
terms=vectorizer.get_feature_names()#단어 집합, 1000개의 단어가 저장됨.
def get_topics(components,feature_names,n=5):
    for idx, topic in enumerate(components):
        print("Topic %d: " %(idx+1),[(feature_names[i],topic[i].round(5)) for i in topic.argsort()[:-n - 1:-1]])
get_topics(svd_model.components_,terms)


Topic 1:  [('like', 0.21378), ('know', 0.20032), ('people', 0.19317), ('think', 0.17807), ('good', 0.15105)]
Topic 2:  [('thanks', 0.3292), ('windows', 0.29094), ('card', 0.18016), ('drive', 0.1739), ('mail', 0.15126)]
Topic 3:  [('game', 0.37161), ('team', 0.32553), ('year', 0.28204), ('games', 0.25416), ('season', 0.18464)]
Topic 4:  [('drive', 0.52804), ('scsi', 0.20035), ('disk', 0.15514), ('hard', 0.15506), ('card', 0.14041)]
Topic 5:  [('windows', 0.4052), ('file', 0.25609), ('window', 0.18057), ('files', 0.1619), ('program', 0.1401)]
Topic 6:  [('chip', 0.16138), ('government', 0.16026), ('mail', 0.15625), ('space', 0.1505), ('information', 0.13575)]
Topic 7:  [('like', 0.67109), ('bike', 0.14268), ('know', 0.11428), ('chip', 0.11058), ('sounds', 0.10398)]
Topic 8:  [('card', 0.45115), ('sale', 0.21607), ('video', 0.21391), ('monitor', 0.14913), ('offer', 0.14872)]
Topic 9:  [('know', 0.44979), ('card', 0.35491), ('chip', 0.17206), ('video', 0.15184), ('government', 0.15053)]
To

In [32]:
#잠재 디리클레 할당
#LDA(잠재 디리클레 할당): LDA는 문서들은 토픽들의 혼합으로 구성. 
#토픽들은 확률분포에 기반하여 단어들을 생성한다. 

tokenized_doc[:5]

0    [well, sure, story, seem, biased, disagree, st...
1    [yeah, expect, people, read, actually, accept,...
2    [although, realize, principle, strongest, poin...
3    [notwithstanding, legitimate, fuss, proposal, ...
4    [well, change, scoring, playoff, pool, unfortu...
Name: clean_doc, dtype: object